name: ci
on:
  push:
    branches: 'master'
    paths: '!**/README.md'
jobs:
  ci:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-11, windows-2019]
        node-version: [14, 16, 18]
        cache: [yarn]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: ${{matrix.cache}}
      - run: yarn
      - run: yarn lint
      - run: yarn build
