name: Publish Docker image
on: [push]
#   release:
#     types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2.3.3

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: notesum/notesum/notesum-frontend
          tag_with_ref: true