on: [push]

name: lint

jobs:
  lint:
    runs-on: self-hosted
    steps:

      # Checkout branch
      - name: Checkout codebase
        uses: actions/checkout@v2.3.3

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: yarn

      - name: Install dependencies
        run: yarn lint
      