on: [push]

name: lint

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      # Checkout branch
      - name: Checkout codebase
        uses: actions/checkout@v2.3.3

      # Make sure we can use node/npm/yarn
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      
      - name: Install npm packages 
        run: yarn

      - name: Lint codebase
        run: yarn lint
      
