on: [push]
name: lint
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install dependencies 
        run: yarn

      - name: Run linter
        run: yarn lint